import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

public class Circle extends Figure 
{
    private static final long serialVersionUID = 2300554085778113857L;  //generated by serialver

    private double r;
    private double x;
    private double y;

    public Circle(double r, double x, double y, String name) throws IllegalArgumentException
    {
        if (r <= 0) throw new IllegalArgumentException("Radius must be >= 0: " + r);

        this.name = name;
        this.r = r;
        this.x = x;
        this.y = y;
    }

    public Circle()
    {
        this.name = "";
        this.r = 1;
        this.x = 0;
        this.y = 0;
    }

    public void set_r(double r) throws IllegalArgumentException
    {
        if (r <= 0) throw new IllegalArgumentException("Radius must be >= 0: " + r);
        this.r = r;
    }

    public double get_r()
    {
        return this.r;
    }

    public void set_x(double x)
    {
        this.x = x;
    }

    public double get_x()
    {
        return this.x;
    }

    public void set_y(double y)
    {
        this.y = y;
    }

    public double get_y()
    {
        return this.y;
    }

    public boolean read(String path)
    {
        try
        {
            FileInputStream file = new FileInputStream(path);
            ObjectInputStream in = new ObjectInputStream(file);

            Circle aux = (Circle)in.readObject();

            in.close();
            file.close();

            this.set_r(aux.r);
            this.set_x(aux.x);
            this.set_y(aux.y);
            this.set_name(aux.name);

            return true;
        }
        catch (Exception e)
        {
            return false;
        }
    }

    public boolean write(String path)
    {
        try
        {
            FileOutputStream file = new FileOutputStream(path);
            ObjectOutputStream out = new ObjectOutputStream(file);

            out.writeObject(this);

            out.close();
            file.close();

            return true;
        }
        catch (Exception e)
        {
            return false;
        }
    }

    public String toString()
    {
        return "Circle " + name + ": " + 
        "r = " + Double.toString(r) + "; " + 
        "x = " + Double.toString(x) + "; " +
        "y = " + Double.toString(y);
    }
}
